baseurl = "/"
enableEmoji = true
footnotereturnlinkcontents = "↩"
googleAnalytics = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
languageCode = "en-us"
theme = "hugo-classic"
title = "Classic"

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
anchorLineNos = false
codeFences = true
guessSyntax = false
hl_Lines = ""
lineAnchors = ""
lineNoStart = 1
lineNos = false
lineNumbersInTable = true
noClasses = true
style = "dracula"
tabWidth = 4

[permalinks]
post = "/post/:year/:month/:day/:slug/"

[menus]
  [[menu.main]]
  name = "Blog"
  pageRef = "/blog"
  weight = 1
  [[menu.main]]
  name = "Contact"
  pageRef = "/contact/"
  weight = 2

[params]
custom_css = ["css/theme-override.css"]
description = "A simple, minimal blog for those who love text."
footer = "༼ つ ╹ ╹ ༽つ"
